# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn
    - run: yarn docs:build
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: docs.danet.land
        remote-user: ${{ secrets.DEPLOYMENT_USER }}
        private-ssh-key: ${{ secrets.DEPLOYMENT_KEY }}
        destination-path: ~/public_html/
        source-path: ./.vitepress/dist/